### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by h3ndro** [Eyepea/redmine_auto_assigned_user#1]
hi, great plugin, defenitely suit my needs. but how to install it?i do rake db:migrate:plugins RAILS_ENV=production and your plugins didn't migrate.

**Comment by ludovic-gasc** [comment]
You don't need to migrate the plugin, only install the files in the right place.

You must configure in the plugins screen.

**Comment by henry1987620** [comment]
Hi,GMLudo,you really should write a little wiki for this plugins.
I meet the same problem with h3ndro .

Thanks very much!

**Comment by henry1987620** [comment]
I tried this plugin,but it not works. 
I have configure in the plugins screen, and add the zh.yml (for Simplified Chinese) to [plugin directory]/config/
locales.
redmine version 1.1.2
linux redhat AS5
apache 2.2.3

**Comment by ludovic-gasc** [comment]
I've made a small documentation: https://github.com/GMLudo/redmine_auto_assigned_user/blob/master/README.textile
