### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by mrniemand** [Eyepea/redmine_auto_assigned_user#3]
I sucessfully installed the plugin, but I'm not sure how to understand the config. I think "Project manager role" defines to which role an issue should be assigned? But what is client roles job?

**Comment by eraldog** [comment]
I have the same question. I really don't understand what "Client roles" means.. Any ideas?

**Comment by ludovic-gasc** [comment]
I've added a small documentation: https://github.com/GMLudo/redmine_auto_assigned_user/blob/master/README.textile

**Comment by eraldog** [comment]
Thank you Ludovic
