### ISSUE TITLE
Error occured: ActionView::Template::Error

### ISSUE THREAD

**Issue by logical-and** [Eyepea/redmine_auto_assigned_user#7]
Whats is the trouble? Thanks!

<pre>
Environment:
  Redmine version                          2.0.2.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.5
  Environment                              production
  Database adapter                         Mysql2
</pre>

<pre>
ActionView::Template::Error (Missing partial settings/auto_assigned_user_settings with {:locale=>[:ru, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb, :rjs]}. Searched in:
  * "/var/www/redmine/plugins/redmine_importer/app/views"
  * "/var/www/redmine/plugins/redmine_auto_assigned_user/app/views"
  * "/var/www/redmine/app/views"
):
    3: <div id="settings">
    4: <%= form_tag({:action => 'plugin'}) do %>
    5: <div class="box tabular">
    6: <%= render :partial => @partial, :locals => {:settings => @settings}%>
    7: </div>
    8: <%= submit_tag l(:button_apply) %>
    9: <% end %>
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__1233964790738922469_53352740'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__1233964790738922469_53352740'
</pre>

**Comment by ludovic-gasc** [comment]
The plugin isn't adapted for Redmine 1.4+ as commented here: #6
